import type { NextPage } from "next";
import Head from "next/head";
import Announcement from "../src/containers/Announcement";
import About from "../src/containers/About";
import Services from "../src/containers/services";
import Contact from "../src/containers/Contact";
import MobileFooter from "../src/containers/Footer";
import OurWork from "../src/containers/OurWork";
import Header from "../src/containers/Header";
import Footer from "../src/containers/Footer/web";
import Copyrights from "../src/containers/Footer/copyrights";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main> */}
      <Header />
      <About />
      <Services />
      <OurWork />
      <Announcement />
      <Contact />
      {/* </main> */}

      <Footer />
      <MobileFooter />
      <Copyrights />
    </div>
  );
};

export default Home;
